### ISSUE TITLE
Cursor isn't inherited

### ISSUE THREAD

**Issue by aljustiet** [ivan-hc/GIMP-appimage#31]
Environment variables are inherited, but the cursor is still Adwaita.

https://github.com/user-attachments/assets/59bfe150-3a35-430c-90be-809085c81b66

OS: Hyprland/Arch

**Comment by ivan-hc** [comment]
Have you got the same issue also with the stable release (I see you use the GIT version)?

**Comment by aljustiet** [comment]
> Have you got the same issue also with the stable release (I see you use the GIT version)?

It has the cursor theme I want, but it doesn't respect the XCUSOR_SIZE variable. I think that the xwayland issue

**Comment by ivan-hc** [comment]
Try to extract the AppImage...
```
./*AppImage --appimage-extract
```
...and edit the AppRun script. Then and see if you can reach the desired result
```
cd ./squashfs-root
./AppRun
```
maybe you need to add a variable or to `--bind-mount` a specific directory.

**Comment by aljustiet** [comment]
> Try to extract the AppImage...
> 
> ```
> ./*AppImage --appimage-extract
> ```
> 
> ...and edit the AppRun script. Then and see if you can reach the desired result
> 
> ```
> cd ./squashfs-root
> ./AppRun
> ```
> 
> maybe you need to add a variable or to `--bind-mount` a specific directory.

`/usr/share/icons` directory?

**Comment by aljustiet** [comment]
❯ ./AppRun --bind-mount /usr/share/icons
Unknown option --bind-mount

**Comment by ivan-hc** [comment]
the change must be done inside the AppRun, you should edit the script, follow the syntax inside the script and retry, for example
```
		--bind-try /media /media \
		--bind-try /mnt /mnt \
		--bind-try /opt /opt \
 		--bind-try /run/media /run/media \
		--bind-try /usr/lib/locale /usr/lib/locale \
		--bind-try /usr/share/fonts /usr/share/fonts \
		--bind-try /usr/share/themes /usr/share/themes \
		--bind-try /var /var \
		"
```
become
```
		--bind-try /media /media \
		--bind-try /mnt /mnt \
		--bind-try /opt /opt \
 		--bind-try /run/media /run/media \
		--bind-try /usr/lib/locale /usr/lib/locale \
		--bind-try /usr/share/fonts /usr/share/fonts \
		--bind-try /usr/share/themes /usr/share/themes \
		--bind-try /var /var \
		--bind-try /usr/share/icons /usr/share/icons \
		"
```

**Comment by aljustiet** [comment]
I tried to modify the AppRun script and run it, but the cursor is still Adwaita; the cursor I set is not inherited.
<details> <summary>GIMP AppRun log</summary>
❯ ./AppRun
GEGL-Message: 12:58:53.315: Module '/usr/lib/gegl-0.4/ff-save.so' load error: libavcodec.so.58: cannot open shared object file: No such file or directory
GEGL-Message: 12:58:53.315: Module '/usr/lib/gegl-0.4/ff-load.so' load error: libavcodec.so.58: cannot open shared object file: No such file or directory
Application icon missing: /usr/share/icons/hicolor/64x64/apps/gimp.png (Failed to open file “/usr/share/icons/hicolor/64x64/apps/gimp.png”: No such file or directory)
Application icon missing: /usr/share/icons/hicolor/scalable/apps/gimp.svg (Failed to open file “/usr/share/icons/hicolor/scalable/apps/gimp.svg”: No such file or directory)
gimp_font_factory_load_names: 3 unsupported fonts were ignored. Set the GIMP_DEBUG_FONTS environment variable for a listing.
GIMP-Warning: Module '/usr/lib/gimp/3.0/modules/libcontroller-linux-input.so' load error: libgudev-1.0.so.0: cannot open shared object file: No such file or directory

set device 'Wayland Pointer' to mode: disabled
pip_system_certs: ERROR: could not register module: No module named 'wrapt'
Traceback (most recent call last):
  File "/usr/lib/gimp/3.0/plug-ins/test-file-plug-ins/test-file-plug-ins.py", line 28, in <module>
    gi.require_version('Gimp', '3.0')
    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'gi' has no attribute 'require_version'
gimp-3.0: LibGimpBase-WARNING: gimp-3.0: gimp_wire_read(): unexpected EOF
pip_system_certs: ERROR: could not register module: No module named 'wrapt'
Traceback (most recent call last):
  File "/usr/lib/gimp/3.0/plug-ins/spyro-plus/spyro-plus.py", line 19, in <module>
    gi.require_version('Gimp', '3.0')
    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'gi' has no attribute 'require_version'
gimp-3.0: LibGimpBase-WARNING: gimp-3.0: gimp_wire_read(): unexpected EOF
pip_system_certs: ERROR: could not register module: No module named 'wrapt'
Traceback (most recent call last):
  File "/usr/lib/gimp/3.0/plug-ins/python-eval/python-eval.py", line 20, in <module>
    gi.require_version('Babl', '0.1')
    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'gi' has no attribute 'require_version'
gimp-3.0: LibGimpBase-WARNING: gimp-3.0: gimp_wire_read(): unexpected EOF
pip_system_certs: ERROR: could not register module: No module named 'wrapt'
Traceback (most recent call last):
  File "/usr/lib/gimp/3.0/plug-ins/python-console/python-console.py", line 20, in <module>
    gi.require_version('Gimp', '3.0')
    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'gi' has no attribute 'require_version'
gimp-3.0: LibGimpBase-WARNING: gimp-3.0: gimp_wire_read(): unexpected EOF
pip_system_certs: ERROR: could not register module: No module named 'wrapt'
Traceback (most recent call last):
  File "/usr/lib/gimp/3.0/plug-ins/palette-to-gradient/palette-to-gradient.py", line 17, in <module>
    gi.require_version('Gimp', '3.0')
    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'gi' has no attribute 'require_version'
gimp-3.0: LibGimpBase-WARNING: gimp-3.0: gimp_wire_read(): unexpected EOF
pip_system_certs: ERROR: could not register module: No module named 'wrapt'
Traceback (most recent call last):
  File "/usr/lib/gimp/3.0/plug-ins/palette-sort/palette-sort.py", line 28, in <module>
    gi.require_version('Babl', '0.1')
    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'gi' has no attribute 'require_version'
gimp-3.0: LibGimpBase-WARNING: gimp-3.0: gimp_wire_read(): unexpected EOF
pip_system_certs: ERROR: could not register module: No module named 'wrapt'
Traceback (most recent call last):
  File "/usr/lib/gimp/3.0/plug-ins/palette-offset/palette-offset.py", line 17, in <module>
    gi.require_version('Gimp', '3.0')
    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'gi' has no attribute 'require_version'
gimp-3.0: LibGimpBase-WARNING: gimp-3.0: gimp_wire_read(): unexpected EOF
pip_system_certs: ERROR: could not register module: No module named 'wrapt'
Traceback (most recent call last):
  File "/usr/lib/gimp/3.0/plug-ins/histogram-export/histogram-export.py", line 43, in <module>
    gi.require_version('Gimp', '3.0')
    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'gi' has no attribute 'require_version'
gimp-3.0: LibGimpBase-WARNING: gimp-3.0: gimp_wire_read(): unexpected EOF
pip_system_certs: ERROR: could not register module: No module named 'wrapt'
Traceback (most recent call last):
  File "/usr/lib/gimp/3.0/plug-ins/gradients-save-as-css/gradients-save-as-css.py", line 26, in <module>
    gi.require_version('Gimp', '3.0')
    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'gi' has no attribute 'require_version'
gimp-3.0: LibGimpBase-WARNING: gimp-3.0: gimp_wire_read(): unexpected EOF
pip_system_certs: ERROR: could not register module: No module named 'wrapt'
Traceback (most recent call last):
  File "/usr/lib/gimp/3.0/plug-ins/foggify/foggify.py", line 18, in <module>
    gi.require_version('Gimp', '3.0')
    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'gi' has no attribute 'require_version'
gimp-3.0: LibGimpBase-WARNING: gimp-3.0: gimp_wire_read(): unexpected EOF
/usr/lib/gimp/3.0/plug-ins/file-xpm/file-xpm: error while loading shared libraries: libXpm.so.4: cannot open shared object file: No such file or directory
gimp-3.0: LibGimpBase-WARNING: gimp-3.0: gimp_wire_read(): unexpected EOF
/usr/lib/gimp/3.0/plug-ins/file-ps/file-ps: error while loading shared libraries: libijs-0.35.so: cannot open shared object file: No such file or directory
gimp-3.0: LibGimpBase-WARNING: gimp-3.0: gimp_wire_read(): unexpected EOF
pip_system_certs: ERROR: could not register module: No module named 'wrapt'
Traceback (most recent call last):
  File "/usr/lib/gimp/3.0/plug-ins/file-openraster/file-openraster.py", line 17, in <module>
    gi.require_version('Gimp', '3.0')
    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'gi' has no attribute 'require_version'
gimp-3.0: LibGimpBase-WARNING: gimp-3.0: gimp_wire_read(): unexpected EOF
/usr/lib/gimp/3.0/plug-ins/file-mng/file-mng: error while loading shared libraries: libmng.so.2: cannot open shared object file: No such file or directory
gimp-3.0: LibGimpBase-WARNING: gimp-3.0: gimp_wire_read(): unexpected EOF
/usr/lib/gimp/3.0/plug-ins/file-jpegxl/file-jpegxl: error while loading shared libraries: libjxl.so.0.11: cannot open shared object file: No such file or directory
gimp-3.0: LibGimpBase-WARNING: gimp-3.0: gimp_wire_read(): unexpected EOF
/usr/lib/gimp/3.0/plug-ins/file-heif/file-heif: error while loading shared libraries: libheif.so.1: cannot open shared object file: No such file or directory
gimp-3.0: LibGimpBase-WARNING: gimp-3.0: gimp_wire_read(): unexpected EOF
/usr/lib/gimp/3.0/plug-ins/file-aa/file-aa: error while loading shared libraries: libaa.so.1: cannot open shared object file: No such file or directory
gimp-3.0: LibGimpBase-WARNING: gimp-3.0: gimp_wire_read(): unexpected EOF
pip_system_certs: ERROR: could not register module: No module named 'wrapt'
Traceback (most recent call last):
  File "/usr/lib/gimp/3.0/plug-ins/colorxhtml/colorxhtml.py", line 25, in <module>
    gi.require_version('Gimp', '3.0')
    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'gi' has no attribute 'require_version'
gimp-3.0: LibGimpBase-WARNING: gimp-3.0: gimp_wire_read(): unexpected EOF
gjs: error while loading shared libraries: libmozjs-128.so: cannot open shared object file: No such file or directory
gimp-3.0: LibGimpBase-WARNING: gimp-3.0: gimp_wire_read(): unexpected EOF
pip_system_certs: ERROR: could not register module: No module named 'wrapt'
Traceback (most recent call last):
  File "/usr/lib/gimp/3.0/extensions/org.gimp.
extension.goat-exercises/goat-exercise-py3.py", line 17, in <module>
    gi.require_version('Gimp', '3.0')
    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'gi' has no attribute 'require_version'
gimp-3.0: LibGimpBase-WARNING: gimp-3.0: gimp_wire_read(): unexpected EOF

(gimp-3.0:239994): Gdk-WARNING **: 12:58:55.631: Server is missing xdg_foreign support
gimp_widget_set_handle_on_mapped: gdk_wayland_window_export_handle() failed. It will not be possible to set windows in other processes as transient to this display shell.

(gimp-3.0:239994): Gdk-WARNING **: 12:58:55.631: Server is missing xdg_foreign support
gimp_widget_set_handle_on_mapped: gdk_wayland_window_export_handle() failed. It will not be possible to set windows in other processes as transient to this display shell.

(gimp-3.0:239994): Gdk-CRITICAL **: 12:58:56.900: gdk_wayland_window_unexport_handle: assertion 'impl->display_server.xdg_exported' failed
set device 'Wayland Finger Scrolling' to mode: disabled

(gimp-3.0:239994): Gdk-WARNING **: 12:59:36.492: Server is missing xdg_foreign support
gimp_widget_set_handle_on_mapped: gdk_wayland_window_export_handle() failed. It will not be possible to set windows in other processes as transient to this display shell.
</details>

**Comment by ivan-hc** [comment]
I have no idea.

@Samueru-sama can you help?

**Comment by Samueru-sama** [comment]
I have no idea.

Seems GIMP will release an official appimage soon anyway.

**Comment by aljustiet** [comment]
Seems that, the cursor should be set using gsettings. In flatpak I can do that by opening the app in interactive shell and running these gsetting commands:
```
gsettings set org.gnome.desktop.interface cursor-theme Bibata-Modern-Classic
gsettings set org.gnome.desktop.interface cursor-size 32
```

**Comment by ivan-hc** [comment]
> Seems that, the cursor should be set using gsettings. In flatpak I can do that by opening the app in interactive shell and running these gsetting commands:
> 
> ```
> gsettings set org.gnome.desktop.interface cursor-theme Bibata-Modern-Classic
> gsettings set org.gnome.desktop.interface cursor-size 32
> ```
> 
> Is it possible to do the same thing for gimp-git AppImage?

what have you done to solve the issue in the AppImage?

**Comment by ivan-hc** [comment]
hi, I updated the appimage yesterday... does the cursor working as you expect now?

**Comment by aljustiet** [comment]
> hi, I updated the Stable AppImage yesterday... does the cursor working as you expect now?

Right now, I'm trying to replace the keyboard on thinkpad t14s gen 3. I'll send the results after replacing.

**Comment by aljustiet** [comment]
> hi, I updated the Stable AppImage yesterday... does the cursor working as you expect now?



> hi, I updated the Stable AppImage yesterday... does the cursor working as you expect now?

`gimp` properly inherits cursor, but `gimp-git` doesn't. I'm on Wayland, so I use the latest version of Gimp to get the Wayland features/fixes as soon as they arrive.

**Comment by ivan-hc** [comment]
As expected, in fact I only have updated gimp stable to Archimage 4.3, that only bundles strictly needed dependencies. I've not updated yet the other two (dev and git).

I can't guarantee for dev, but for git I'll try my best tomorrow.

**Comment by ivan-hc** [comment]
@aljustiet give it a try https://github.com/ivan-hc/GIMP-appimage/releases/tag/continuous-git

**Comment by ivan-hc** [comment]
@aljustiet any news?

**Comment by aljustiet** [comment]
> [@aljustiet](https://github.com/aljustiet) any news?

The cursor hasn't changed and has become tiny.

**Comment by ivan-hc** [comment]
Well, yesterday I noticed in Handbrake that alternative themes are not inherited too https://github.com/ivan-hc/Handbrake-appimage/issues/2 maybe the issue is related.

Has we have done there, you should provide a log urig LD_DEBUG=libs and LD_DEBUG=files, maybe we may know more about this strange behaviour.

**Comment by aljustiet** [comment]
> Well, yesterday I noticed in Handbrake that alternative themes are not inherited too [ivan-hc/Handbrake-appimage#2](https://github.com/ivan-hc/Handbrake-appimage/issues/2) maybe the issue is related.
> 
> Has we have done there, you should provide a log using LD_DEBUG=libs and LD_DEBUG=files, maybe we may know more about this strange behaviour.

The logs are very long.

**Comment by ivan-hc** [comment]
> The logs are very long. It doesn't fit to my terminal output limit

```
LD_DEBUG=libs gimp-git > loglibs.txt
LD_DEBUG=files gimp-git > logfiles.txt
```

**Comment by aljustiet** [comment]
> > The logs are very long. It doesn't fit to my terminal output limit
> 
> ```
> LD_DEBUG=libs gimp-git > loglibs.txt
> LD_DEBUG=files gimp-git > logfiles.txt
> ```

[logfiles.txt](https://github.com/user-attachments/files/18636563/logfiles.txt)
[loglibs.txt](https://github.com/user-attachments/files/18636562/loglibs.txt)

**Comment by ivan-hc** [comment]
These are the errors I found
```
/home/aljustiet/.profile: line 9: wal: command not found
```
the above is related to a command that is not included in the AppImage... I don't think its the case, since it is an obsolete package https://github.com/dylanaraps/wal also available on the AUR, but no more updated since 2017 https://aur.archlinux.org/packages/wal-git

```
    417620:	file=/usr/lib/gimp/3.0/modules/libdisplay-filter-high-contrast.so [0];  destroying link map
set device 'Wayland Pointer' to mode: disabled
```
I suppose you are using Wayland... I would like to do a test, but I have not Wayland (or better, I have xfce4.20, but the wayland support is experimental... that means it still sucks, I tested it... I lasted two minutes, then switched back to x11).

Btw it is interesting that the error talks about a Pointer. Maybe the solution is there.

```

(gimp:417620): Gdk-WARNING **: 09:10:31.784: Server is missing xdg_foreign support
gimp_widget_set_handle_on_mapped: gdk_wayland_window_export_handle() failed. It will not be possible to set windows in other processes as transient to this display shell.

(gimp:417620): Gdk-WARNING **: 09:10:31.784: Server is missing xdg_foreign support
gimp_widget_set_handle_on_mapped: gdk_wayland_window_export_handle() failed. It will not be possible to set windows in other processes as transient to this display shell.

(gimp:417620): Gdk-CRITICAL **: 09:10:33.342: gdk_wayland_window_unexport_handle: assertion 'impl->display_server.xdg_exported_v2 || impl->display_server.xdg_exported_v1' failed
```
Still another wayland-related issue.

---------------------------------

Well, the second one is the more interesting among the two.

On your side I would start investigate if the issue appears with other themes.

**Comment by ivan-hc** [comment]
About wayland support, I just checked... and the gimp-git appimage has more libraries than gimp stable... the additional ones are related to some gstreamer process, I'm not sure, they ave "gst" in the name. But for all the rest, they are the same.

Among differences for other files, well... there is an xml file only for gimp stable

![Image](https://github.com/user-attachments/assets/8f18a652-3e6f-4acd-a55f-c92e72ef8e95)

...but if it was in the /usr/share/gimp directory in stable, same should be for the git version.

Among pictures for icon themes, there are only 4 files for gimp-git, the first 4 on top

![Image](https://github.com/user-attachments/assets/f7f834c2-45fb-4ce4-9e14-46cd04bdcae9)

...but I don't think it is a relevant info.

---------------------------

Anyway, the issue seems to be related to Wayland support for custom themes.

Again, do the test with another theme... and maybe repeat the test into a X11 session.

**Comment by ivan-hc** [comment]
Also, is your icon theme installed system-wide?

Maybe try to symlink the "cursors" directory of your theme in $HOME/.icons/default and see if something changes.

**Comment by aljustiet** [comment]
> About wayland support, I just checked... and the gimp-git appimage has more libraries than gimp stable... the additional ones are related to some gstreamer process, I'm not sure, they ave "gst" in the name. But for all the rest, they are the same.
> 
> Among differences for other files, well... there is an xml file only for gimp stable
> 
> ![Image](https://github.com/user-attachments/assets/8f18a652-3e6f-4acd-a55f-c92e72ef8e95)
> 
> ...but if it was in the /usr/share/gimp directory in stable, same should be for the git version.
> 
> Among pictures for icon themes, there are only 4 files for gimp-git, the first 4 on top
> 
> ![Image](https://github.com/user-attachments/assets/f7f834c2-45fb-4ce4-9e14-46cd04bdcae9)
> 
> ...but I don't think it is a relevant info.
> 
> Anyway, the issue seems to be related to Wayland support for custom themes.
> 
> Again, do the test with another theme... and maybe repeat the test into a X11 session.

I tried to launch it with dwm/X, and it properly inherited bibata cursor there.

**Comment by ivan-hc** [comment]
> I tried to launch it with dwm/X, and it properly inherited bibata cursor there.

sorry, I've not understand... does it work with X11?

**Comment by ivan-hc** [comment]
So the issue shous up only when you run the appimage in a wayland session, isn't it?

If so, I don't really know how to help. You should compile the archimage script into a dedicated directory and test what are the files missing, for example by copying the archlinux/.junest/usr/lib directory in place of the gimp-git.AppDir/.junest/usr/lib counterpart to see if the issue disappears.

I can't do much. Note that gimp-git is also an experimental software, so many new features that are in gimp stable are different from the ones in gimp-git.

Maybe all libadwaita/gtk4 related libraris need to be included. I'm not sure.

Please, follow the instructions on the README of this repo https://github.com/ivan-hc/ArchImage and perform your tests.

**Comment by ivan-hc** [comment]
I'm closing due to inactivity
